
FROM node:20-alpine


WORKDIR /usr/src/app


COPY package.json ./
COPY package-lock.json ./


RUN npm install nodemailer ejs amqplib --production


COPY . .


CMD ["sh", "-c", "sleep 40 && node workers/emailWorker.js"]